excluded:
  - Vendor
disabled_rules:
  - function_body_length
  - line_length
  - cyclomatic_complexity
  - large_tuple

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - empty_collection_literal
  - empty_count
  - empty_string
  - file_name_no_space
  - file_types_order
  - force_unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
#  - unused_import
# Rule-specific config
force_try:
  severity: warning
force_cast:
  severity: warning
identifier_name:
  min_length:
    warning: 2
  allowed_symbols: "_"
